version: '3.5'

services:
  app:
    image: vvasileva/frontend_project_lvl12
    restart: always
    ports: ['8082:3000']
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:8082 || echo 1
      interval: 30s
      timeout: 3s
      retries: 12